### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by Deftu** [ChachyDev/Lorem#1]
This is most likely stupid to ask, or possibly redundant, but a README file would be nice as there's no proper context as to what this is for people who are unacquainted with the project.

**Comment by ChachyDev** [comment]
Sure, I need to clean up the project anyway :)

**Comment by Deftu** [comment]
> Sure, I need to clean up the project anyway :)

Thanks!

**Comment by ChachyDev** [comment]
Fixed in [44d9070](https://github.com/ChachyDev/Lorem/commit/44d90702973d319e83506d20d1b474d81eb67072)
